spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/iris-hyperion
      username: root
      password: 123456
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: true
